// Hand-maintained public facts for the best-known companies. Anything unknown is
// left out and hidden gracefully on the page. Keyed by the stored company name.
// `description` is a verified, factual one-liner of what the company does — no
// funding amounts, no CEO/people facts, nothing that isn't publicly obvious.
export interface CompanyMeta {
  hqCity?: string;
  website?: string; // bare domain
  founded?: number;
  stage?: string; // "Series A/B/C…", "Public", "Private"
  description?: string; // short factual one-liner; hidden if absent
}

export const COMPANY_META: Record<string, CompanyMeta> = {
  Adyen: { hqCity: "Amsterdam", website: "adyen.com", founded: 2006, stage: "Public", description: "Global payments platform for enterprise merchants." },
  Monzo: { hqCity: "London", website: "monzo.com", founded: 2015, stage: "Private", description: "App-based challenger bank." },
  Wise: { hqCity: "London", website: "wise.com", founded: 2011, stage: "Public", description: "Low-cost international money transfers." },
  N26: { hqCity: "Berlin", website: "n26.com", founded: 2013, stage: "Private", description: "Mobile-first challenger bank." },
  GoCardless: { hqCity: "London", website: "gocardless.com", founded: 2011, stage: "Private", description: "Bank-to-bank recurring payments." },
  Qonto: { hqCity: "Paris", website: "qonto.com", founded: 2016, stage: "Private", description: "Business banking for SMEs and freelancers." },
  Pleo: { hqCity: "Copenhagen", website: "pleo.io", founded: 2015, stage: "Private", description: "Company spending cards and expense management." },
  SumUp: { hqCity: "London", website: "sumup.com", founded: 2012, stage: "Private", description: "Card readers and payments for small merchants." },
  Mollie: { hqCity: "Amsterdam", website: "mollie.com", founded: 2004, stage: "Private", description: "Online payments for European businesses." },
  "Trade Republic": { hqCity: "Berlin", website: "traderepublic.com", founded: 2015, stage: "Private", description: "Mobile broker for commission-free investing." },
  Pennylane: { hqCity: "Paris", website: "pennylane.com", founded: 2020, stage: "Private", description: "Accounting and finance platform for SMEs." },
  Tide: { hqCity: "London", website: "tide.co", founded: 2015, stage: "Private", description: "Business banking and admin for SMEs." },
  Form3: { hqCity: "London", website: "form3.tech", founded: 2016, stage: "Private", description: "Cloud payments processing for banks." },
  Griffin: { hqCity: "London", website: "griffin.com", founded: 2017, stage: "Private", description: "Banking-as-a-service platform." },
  Zopa: { hqCity: "London", website: "zopa.com", founded: 2005, stage: "Private", description: "Digital bank, formerly a P2P lender." },
  Marshmallow: { hqCity: "London", website: "marshmallow.com", founded: 2017, stage: "Private", description: "Car insurance for underserved drivers." },
  ComplyAdvantage: { hqCity: "London", website: "complyadvantage.com", founded: 2014, stage: "Private", description: "AML and financial-crime risk data." },
  Bunq: { hqCity: "Amsterdam", website: "bunq.com", founded: 2012, stage: "Private", description: "Mobile bank for digital nomads." },
  Raisin: { hqCity: "Berlin", website: "raisin.com", founded: 2012, stage: "Private", description: "Savings and deposits marketplace." },
  Payhawk: { hqCity: "London", website: "payhawk.com", founded: 2018, stage: "Private", description: "Corporate cards and spend management." },
  Zilch: { hqCity: "London", website: "zilch.com", founded: 2018, stage: "Private", description: "Buy-now-pay-later and rewards app." },
  Ledger: { hqCity: "Paris", website: "ledger.com", founded: 2014, stage: "Private", description: "Crypto hardware wallets and security." },
  PayFit: { hqCity: "Paris", website: "payfit.com", founded: 2015, stage: "Private", description: "Payroll and HR software for SMEs." },
  Swile: { hqCity: "Paris", website: "swile.co", founded: 2018, stage: "Private", description: "Employee benefits and meal-voucher cards." },

  "Mistral AI": { hqCity: "Paris", website: "mistral.ai", founded: 2023, stage: "Private", description: "Open-weight large language models." },
  ElevenLabs: { hqCity: "London", website: "elevenlabs.io", founded: 2022, stage: "Private", description: "AI voice generation and audio." },
  Synthesia: { hqCity: "London", website: "synthesia.io", founded: 2017, stage: "Private", description: "AI avatar video generation." },
  Wayve: { hqCity: "London", website: "wayve.ai", founded: 2017, stage: "Private", description: "Embodied AI for self-driving vehicles." },
  DeepL: { hqCity: "Cologne", website: "deepl.com", founded: 2017, stage: "Private", description: "AI translation and writing tools." },
  Helsing: { hqCity: "Munich", website: "helsing.ai", founded: 2021, stage: "Private", description: "AI software for defence." },
  Graphcore: { hqCity: "Bristol", website: "graphcore.ai", founded: 2016, stage: "Private", description: "AI accelerator chips (IPUs)." },

  GitLab: { website: "gitlab.com", founded: 2014, stage: "Public", description: "DevOps platform for the software lifecycle." },
  "Grafana Labs": { website: "grafana.com", founded: 2014, stage: "Private", description: "Open-source observability and dashboards." },
  PostHog: { website: "posthog.com", founded: 2020, stage: "Private", description: "Open-source product analytics." },
  n8n: { hqCity: "Berlin", website: "n8n.io", founded: 2019, stage: "Private", description: "Workflow automation for technical teams." },
  Tinybird: { hqCity: "Madrid", website: "tinybird.co", founded: 2019, stage: "Private", description: "Real-time analytics APIs over data." },
  Algolia: { hqCity: "Paris", website: "algolia.com", founded: 2012, stage: "Private", description: "Hosted search and discovery API." },
  Celonis: { hqCity: "Munich", website: "celonis.com", founded: 2011, stage: "Private", description: "Process mining and execution management." },
  Dataiku: { hqCity: "Paris", website: "dataiku.com", founded: 2013, stage: "Private", description: "Enterprise data science and AI platform." },
  Aircall: { hqCity: "Paris", website: "aircall.io", founded: 2014, stage: "Private", description: "Cloud phone system for teams." },
  Camunda: { hqCity: "Berlin", website: "camunda.com", founded: 2013, stage: "Private", description: "Process orchestration and automation." },
  Contentful: { hqCity: "Berlin", website: "contentful.com", founded: 2013, stage: "Private", description: "Headless content management platform." },
  Typeform: { hqCity: "Barcelona", website: "typeform.com", founded: 2012, stage: "Private", description: "Conversational forms and surveys." },
  Pipedrive: { hqCity: "Tallinn", website: "pipedrive.com", founded: 2010, stage: "Private", description: "Sales CRM for small businesses." },
  Leapsome: { hqCity: "Berlin", website: "leapsome.com", founded: 2016, stage: "Private", description: "Performance, engagement and learning HR platform." },

  Doctolib: { hqCity: "Paris", website: "doctolib.fr", founded: 2013, stage: "Private", description: "Online medical booking and telehealth." },
  Alan: { hqCity: "Paris", website: "alan.com", founded: 2016, stage: "Private", description: "Digital health insurance and care." },
  "Flo Health": { hqCity: "London", website: "flo.health", founded: 2015, stage: "Private", description: "Women's health and cycle-tracking app." },
  Oura: { hqCity: "Oulu", website: "ouraring.com", founded: 2013, stage: "Private", description: "Smart ring for sleep and health." },
  Personio: { hqCity: "Munich", website: "personio.com", founded: 2015, stage: "Private", description: "HR and payroll software for SMEs." },
  HiBob: { hqCity: "London", website: "hibob.com", founded: 2015, stage: "Private", description: "HR platform for mid-size firms." },

  Deliveroo: { hqCity: "London", website: "deliveroo.co.uk", founded: 2013, stage: "Public", description: "Food delivery marketplace." },
  HelloFresh: { hqCity: "Berlin", website: "hellofresh.com", founded: 2011, stage: "Public", description: "Meal-kit subscription service." },
  "Delivery Hero": { hqCity: "Berlin", website: "deliveryhero.com", founded: 2011, stage: "Public", description: "Global food-delivery holding company." },
  Wolt: { hqCity: "Helsinki", website: "wolt.com", founded: 2014, stage: "Public", description: "Food and retail delivery across EMEA." },
  GetYourGuide: { hqCity: "Berlin", website: "getyourguide.com", founded: 2009, stage: "Private", description: "Marketplace for tours and experiences." },
  "Back Market": { hqCity: "Paris", website: "backmarket.com", founded: 2014, stage: "Private", description: "Refurbished electronics marketplace." },
  "Vestiaire Collective": { hqCity: "Paris", website: "vestiairecollective.com", founded: 2009, stage: "Private", description: "Pre-owned luxury fashion marketplace." },
  Farfetch: { hqCity: "London", website: "farfetch.com", founded: 2007, stage: "Public", description: "Online luxury fashion marketplace." },
  Trustpilot: { hqCity: "Copenhagen", website: "trustpilot.com", founded: 2007, stage: "Public", description: "Consumer reviews platform." },
  Skyscanner: { hqCity: "Edinburgh", website: "skyscanner.net", founded: 2003, stage: "Public", description: "Flight and travel search engine." },
  Sorare: { hqCity: "Paris", website: "sorare.com", founded: 2018, stage: "Private", description: "Fantasy sports collectibles game." },
  Spotify: { hqCity: "Stockholm", website: "spotify.com", founded: 2006, stage: "Public", description: "Audio streaming platform." },
  Truecaller: { hqCity: "Stockholm", website: "truecaller.com", founded: 2009, stage: "Public", description: "Caller ID and spam-blocking app." },
  Cognite: { hqCity: "Oslo", website: "cognite.com", founded: 2016, stage: "Private", description: "Industrial data and AI platform." },

  // Logo-coverage sweep — domains for the top companies by posting count.
  ICEYE: { website: "iceye.com", description: "Radar satellite imaging." },
  "Nord Security": { website: "nordsecurity.com", description: "Consumer cybersecurity, incl. NordVPN." },
  Fresha: { website: "fresha.com", description: "Booking software for salons and spas." },
  Satispay: { website: "satispay.com", description: "Mobile payments network in Italy." },
  Rohlik: { website: "rohlik.group", description: "Online grocery delivery in central Europe." },
  Intercom: { website: "intercom.com", description: "AI customer-service and messaging platform." },
  Veepee: { website: "veepee.com", description: "Flash-sales e-commerce." },
  Proton: { website: "proton.me", description: "Encrypted email and privacy tools." },
  Faculty: { website: "faculty.ai", description: "Applied AI and data science." },
  UiPath: { website: "uipath.com", description: "Robotic process automation." },
  ASOS: { website: "asos.com", description: "Online fashion retailer." },
  Pigment: { website: "pigment.com", description: "Business planning and forecasting platform." },
  Peak: { website: "peak.ai", description: "AI for commercial decision-making." },
  Nexthink: { website: "nexthink.com", description: "Digital employee-experience management." },
  "Free Now": { website: "free-now.com", description: "Ride-hailing and mobility app." },
  Solita: { website: "solita.fi", description: "Digital and data consultancy." },
  "Too Good To Go": { website: "toogoodtogo.com", description: "Surplus-food marketplace against waste." },
  Shine: { website: "shine.fr", description: "Business banking for freelancers." },
  Similarweb: { website: "similarweb.com", description: "Web and market intelligence data." },
  Trainline: { website: "thetrainline.com", description: "Train and coach ticketing app." },
  "Aikido Security": { website: "aikido.dev", description: "Developer-first security scanning." },
  Scaleway: { website: "scaleway.com", description: "European cloud infrastructure." },
  "Avi Medical": { website: "avimedical.com", description: "Tech-enabled medical practices." },
  Lighthouse: { website: "mylighthouse.com", description: "Commercial data for hotels." },
  Skello: { website: "skello.io", description: "Staff scheduling and workforce management." },
  DocPlanner: { website: "docplanner.com", description: "Doctor booking and practice software." },
  Bitpanda: { website: "bitpanda.com", description: "Retail crypto and investing platform." },
  Agicap: { website: "agicap.com", description: "Cashflow management for SMEs." },
  Yousign: { website: "yousign.com", description: "European e-signature platform." },
  ML6: { website: "ml6.eu", description: "Machine-learning consultancy." },
  Coverflex: { website: "coverflex.com", description: "Employee benefits and compensation platform." },
  Quinyx: { website: "quinyx.com", description: "Workforce management and scheduling." },
  Rossum: { website: "rossum.ai", description: "AI document data extraction." },
  Keboola: { website: "keboola.com", description: "Data operations platform." },
  Emplifi: { website: "emplifi.io", description: "Customer-experience and social marketing." },
  Vinted: { website: "vinted.com", description: "Second-hand fashion marketplace." },
  Otovo: { website: "otovo.com", description: "Residential solar marketplace." },
  Vipps: { website: "vipps.no", description: "Mobile payments app in Norway." },
  // Famous tech names being scraped in (public boards) — logos ready on arrival.
  Databricks: { website: "databricks.com", description: "Data lakehouse and AI platform." }, OpenAI: { website: "openai.com", description: "AI research and products, incl. ChatGPT." },
  Anthropic: { website: "anthropic.com", description: "AI safety research; the Claude models." }, Snowflake: { website: "snowflake.com", description: "Cloud data-warehouse platform." },
  MongoDB: { website: "mongodb.com", description: "Document database platform." }, Cloudflare: { website: "cloudflare.com", description: "Web performance and security network." },
  Datadog: { website: "datadoghq.com", description: "Cloud monitoring and observability." }, Airbnb: { website: "airbnb.com", description: "Short-stay and experiences marketplace." },
  Pinterest: { website: "pinterest.com", description: "Visual discovery and bookmarking." }, Palantir: { website: "palantir.com", description: "Data analytics for enterprise and government." },
  Canva: { website: "canva.com", description: "Online graphic-design platform." }, Figma: { website: "figma.com", description: "Collaborative interface-design tool." },
  Cohere: { website: "cohere.com", description: "Enterprise large language models." }, Elastic: { website: "elastic.co", description: "Search and observability (Elasticsearch)." },
  Twilio: { website: "twilio.com", description: "Programmable communications APIs." }, Grab: { website: "grab.com", description: "Super-app for Southeast Asia." },
  Freshworks: { website: "freshworks.com", description: "Customer and employee software suite." }, Docker: { website: "docker.com", description: "Container tooling for developers." },
  Miro: { website: "miro.com", description: "Online collaborative whiteboard." }, Asana: { website: "asana.com", description: "Work and project management." },
  Supercell: { website: "supercell.com", description: "Mobile games studio." },
  // --- logo sweep 2: verified domains (DDG-200 + homepage title match) ---
  "11 bit studios": { website: "11bitstudios.com" },
  "1Komma5": { website: "1komma5.com" },
  "360Learning": { website: "360learning.com" },
  "3Pillar Global": { website: "3pillarglobal.com" },
  Accesa: { website: "accesa.co" },
  Accurx: { website: "accurx.com" },
  Adform: { website: "adform.com" },
  Adjust: { website: "adjust.ai" },
  Advenica: { website: "advenica.com" },
  Allego: { website: "allego.eu" },
  "Alva Labs": { website: "alvalabs.io" },
  Amboss: { website: "amboss.com" },
  Anybotics: { website: "anybotics.com" },
  Anyfin: { website: "anyfin.com" },
  Apaleo: { website: "apaleo.com" },
  Apify: { website: "apify.com" },
  Ardoq: { website: "ardoq.com" },
  Attio: { website: "attio.com" },
  Auterion: { website: "auterion.com" },
  "Avalanche Studios": { website: "avalanchestudios.com" },
  Beamery: { website: "beamery.com" },
  Bekk: { website: "bekk.dev" },
  "Bigger Games": { website: "biggergames.com" },
  Blablacar: { website: "blablacar.com" },
  "Bob W": { website: "bobw.io" },
  Brainlab: { website: "brainlab.com" },
  Brevo: { website: "brevo.io" },
  Bryter: { website: "bryter.com" },
  Bunch: { website: "bunch.ai" },
  "Butternut Box": { website: "butternutbox.pl" },
  Cabify: { website: "cabify.com" },
  Careem: { website: "careem.com" },
  Cazoo: { website: "cazoo.fi" },
  CEiiA: { website: "ceiia.com" },
  Cellink: { website: "cellink.com" },
  Centra: { website: "centra.com" },
  Chaos: { website: "chaos.com" },
  Chip: { website: "chip.app" },
  Choco: { website: "choco.com" },
  CitySwift: { website: "cityswift.com" },
  "Clarity AI": { website: "clarityai.co" },
  ClearBank: { website: "clearbank.tech" },
  Codit: { website: "codit.tech" },
  Cognism: { website: "cognism.com" },
  Collibra: { website: "collibra.ai" },
  Contentsquare: { website: "contentsquare.com" },
  Crisp: { website: "crisp.com" },
  CYE: { website: "cye.pl" },
  Cymulate: { website: "cymulate.com" },
  Datasnipper: { website: "datasnipper.com" },
  DeepJudge: { website: "deepjudge.ai" },
  Deliverect: { website: "deliverect.com" },
  Descope: { website: "descope.tech" },
  Didomi: { website: "didomi.io" },
  Docebo: { website: "docebo.de" },
  Doctrine: { website: "doctrine.co" },
  Doodle: { website: "doodle.com" },
  "Dream Games": { website: "dreamgames.com" },
  Dubizzle: { website: "dubizzle.ai" },
  Dust: { website: "dust.co" },
  DVT: { website: "dvt.com" },
  Easee: { website: "easee.com" },
  Effectory: { website: "effectory.com" },
  Effy: { website: "effy.ai" },
  Egym: { website: "egym.com" },
  ELEKS: { website: "eleks.com" },
  Elliptic: { website: "elliptic.co" },
  Eneba: { website: "eneba.com" },
  Enode: { website: "enode.com" },
  Enpal: { website: "enpal.com" },
  "Epidemic Sound": { website: "epidemicsound.com" },
  Evernest: { website: "evernest.co" },
  Eversports: { website: "eversports.ai" },
  Exotrail: { website: "exotrail.com" },
  "Eye Security": { website: "eyesecurity.nl" },
  Famly: { website: "famly.co" },
  Farseer: { website: "farseer.fr" },
  Fastned: { website: "fastned.co" },
  Filigran: { website: "filigran.io" },
  Fireblocks: { website: "fireblocks.de" },
  Flix: { website: "flix.com" },
  Flower: { website: "flower.io" },
  Folio: { website: "folio.ai" },
  Fonoa: { website: "fonoa.com" },
  Forter: { website: "forter.dev" },
  Forto: { website: "forto.com" },
  Freetrade: { website: "freetrade.io" },
  Frequentis: { website: "frequentis.com" },
  Frontify: { website: "frontify.com" },
  Gcore: { website: "gcore.com" },
  Gearset: { website: "gearset.com" },
  Gelato: { website: "gelato.dev" },
  Glia: { website: "glia.com" },
  Gloat: { website: "gloat.app" },
  GoodData: { website: "gooddata.com" },
  "Goodgame Studios": { website: "goodgamestudios.com" },
  Goodlord: { website: "goodlord.com" },
  GoStudent: { website: "gostudent.de" },
  Gousto: { website: "gousto.app" },
  GreenFlux: { website: "greenflux.com" },
  Grover: { website: "grover.com" },
  Guardsquare: { website: "guardsquare.com" },
  Gymshark: { website: "gymshark.pl" },
  "H Company": { website: "hcompany.ai" },
  Hadrian: { website: "hadrian.io" },
  Heetch: { website: "heetch.com" },
  "Hinge Health": { website: "hingehealth.com" },
  Hived: { website: "hived.ai" },
  Holded: { website: "holded.io" },
  Hostaway: { website: "hostaway.com" },
  Hostinger: { website: "hostinger.com" },
  Hoxhunt: { website: "hoxhunt.com" },
  Humaans: { website: "humaans.io" },
  HUUB: { website: "huub.com" },
  IDnow: { website: "idnow.io" },
  Improbable: { website: "improbable.com" },
  "In The Pocket": { website: "inthepocket.com" },
  Infraspeak: { website: "infraspeak.io" },
  Innovecs: { website: "innovecs.com" },
  Inovex: { website: "inovex.com" },
  Insta: { website: "insta.de" },
  Instabee: { website: "instabee.app" },
  Instacart: { website: "instacart.com" },
  Instagrid: { website: "instagrid.pl" },
  IQM: { website: "iqm.com" },
  "Isabel Group": { website: "isabelgroup.com" },
  "Isar Aerospace": { website: "isaraerospace.com" },
  ISISpace: { website: "isispace.nl" },
  "Isomorphic Labs": { website: "isomorphiclabs.com" },
  Ivalua: { website: "ivalua.es" },
  Iyzico: { website: "iyzico.com" },
  JFrog: { website: "jfrog.com" },
  Jobandtalent: { website: "jobandtalent.fi" },
  JobTeaser: { website: "jobteaser.com" },
  Journi: { website: "journi.co" },
  "Kaizen Gaming": { website: "kaizengaming.com" },
  Kaluza: { website: "kaluza.com" },
  Keepit: { website: "keepit.com" },
  Kestra: { website: "kestra.io" },
  Kinexon: { website: "kinexon.com" },
  Klara: { website: "klara.dev" },
  Klaxoon: { website: "klaxoon.com" },
  Kleos: { website: "kleos.com" },
  Knowunity: { website: "knowunity.com" },
  Kota: { website: "kota.com" },
  Langdock: { website: "langdock.com" },
  Leaseweb: { website: "leaseweb.io" },
  Ledgy: { website: "ledgy.com" },
  Legora: { website: "legora.com" },
  Lemonade: { website: "lemonade.com" },
  Lendable: { website: "lendable.com" },
  Lexroom: { website: "lexroom.ai" },
  Luscii: { website: "luscii.com" },
  Malt: { website: "malt.io" },
  "Mama Money": { website: "mamamoney.com" },
  "Marvel Fusion": { website: "marvelfusion.com" },
  Masabi: { website: "masabi.com" },
  Matera: { website: "matera.com" },
  Meilisearch: { website: "meilisearch.com" },
  Melio: { website: "melio.com" },
  Mendix: { website: "mendix.it" },
  Mentimeter: { website: "mentimeter.fi" },
  Metaview: { website: "metaview.co" },
  "Mind Foundry": { website: "mindfoundry.com" },
  Mintos: { website: "mintos.com" },
  Miodottore: { website: "miodottore.it" },
  "Momo Medical": { website: "momomedical.com" },
  "Moon Active": { website: "moonactive.com" },
  Moonpig: { website: "moonpig.com" },
  Motorway: { website: "motorway.com" },
  Multiverse: { website: "multiverse.com" },
  "Multiverse Computing": { website: "multiversecomputing.com" },
  MyTomorrows: { website: "mytomorrows.com" },
  "N-iX": { website: "nix.dev" },
  Nabla: { website: "nabla.com" },
  NavVis: { website: "navvis.com" },
  Nearform: { website: "nearform.com" },
  Nelly: { website: "nelly.ai" },
  Neo4j: { website: "neo4j.com" },
  Neon: { website: "neon.com" },
  Netconomy: { website: "netconomy.ai" },
  Netlight: { website: "netlight.se" },
  Nevis: { website: "nevis.com" },
  Nium: { website: "nium.com" },
  Nmbrs: { website: "nmbrs.com" },
  "No Isolation": { website: "noisolation.com" },
  Nomagic: { website: "nomagic.com" },
  Northwave: { website: "northwave.ai" },
  Nory: { website: "nory.ai" },
  Notion: { website: "notion.com" },
  "Nozomi Networks": { website: "nozominetworks.com" },
  nShift: { website: "nshift.com" },
  Numa: { website: "numa.com" },
  Obilet: { website: "obilet.com" },
  OBRIO: { website: "obrio.co" },
  Ohme: { website: "ohme.fr" },
  Origo: { website: "origo.io" },
  Ornikar: { website: "ornikar.com" },
  Outfit7: { website: "outfit7.com" },
  "OVO Energy": { website: "ovoenergy.com" },
  Owkin: { website: "owkin.com" },
  Oxylabs: { website: "oxylabs.io" },
  Paddle: { website: "paddle.io" },
  "Paradox Interactive": { website: "paradoxinteractive.com" },
  Parloa: { website: "parloa.com" },
  Pasqal: { website: "pasqal.com" },
  Payflows: { website: "payflows.io" },
  Payoneer: { website: "payoneer.io" },
  Phished: { website: "phished.io" },
  Photoroom: { website: "photoroom.com" },
  PhysicsX: { website: "physicsx.ai" },
  Pineapple: { website: "pineapple.co" },
  Planhat: { website: "planhat.com" },
  PlanRadar: { website: "planradar.com" },
  Pliant: { website: "pliant.fi" },
  Podimo: { website: "podimo.com" },
  Polestar: { website: "polestar.com" },
  Poolside: { website: "poolside.ai" },
  Powens: { website: "powens.com" },
  Powerdot: { website: "powerdot.eu" },
  PQShield: { website: "pqshield.com" },
  Preply: { website: "preply.com" },
  "Property Finder": { website: "propertyfinder.com" },
  "Proxima Fusion": { website: "proximafusion.com" },
  PVcase: { website: "pvcase.com" },
  Qashio: { website: "qashio.com" },
  Qred: { website: "qred.com" },
  Quantexa: { website: "quantexa.com" },
  Rain: { website: "rain.com" },
  Reaktor: { website: "reaktor.com" },
  Reco: { website: "reco.io" },
  Redis: { website: "redis.com" },
  Refurbed: { website: "refurbed.com" },
  reMarkable: { website: "remarkable.com" },
  Restream: { website: "restream.com" },
  "Rise Up": { website: "riseup.ai" },
  Riskified: { website: "riskified.app" },
  Riverlane: { website: "riverlane.de" },
  RIVR: { website: "rivr.io" },
  "Salt Security": { website: "saltsecurity.ai" },
  Scandit: { website: "scandit.nl" },
  Secfix: { website: "secfix.com" },
  Sedna: { website: "sedna.com" },
  Seedtag: { website: "seedtag.com" },
  Semperis: { website: "semperis.com" },
  Sendcloud: { website: "sendcloud.dev" },
  Sensei: { website: "sensei.com" },
  Sensorfact: { website: "sensorfact.eu" },
  Sereact: { website: "sereact.ai" },
  Seyna: { website: "seyna.eu" },
  Shoptet: { website: "shoptet.ai" },
  Showpad: { website: "showpad.de" },
  Shypple: { website: "shypple.com" },
  Signicat: { website: "signicat.com" },
  Skytree: { website: "skytree.pl" },
  Solidgate: { website: "solidgate.com" },
  Sona: { website: "sona.com" },
  Sonio: { website: "sonio.ai" },
  SoSafe: { website: "sosafe.io" },
  Span: { website: "span.dev" },
  Speedy: { website: "speedy.io" },
  Sportradar: { website: "sportradar.app" },
  "Spyke Games": { website: "spykegames.com" },
  Squarespace: { website: "squarespace.com" },
  Staffbase: { website: "staffbase.com" },
  Stegra: { website: "stegra.eu" },
  Storyblok: { website: "storyblok.com" },
  STRV: { website: "strv.ai" },
  Studytube: { website: "studytube.com" },
  Sumsub: { website: "sumsub.com" },
  Sunday: { website: "sunday.ai" },
  Superside: { website: "superside.com" },
  Surfshark: { website: "surfshark.com" },
  "Svea Solar": { website: "sveasolar.com" },
  Swan: { website: "swan.com" },
  Swarco: { website: "swarco.com" },
  "Sweet Security": { website: "sweetsecurity.com" },
  Taboola: { website: "taboola.com" },
  Tacto: { website: "tacto.com" },
  "Tandem Health": { website: "tandemhealth.ai" },
  Testlio: { website: "testlio.com" },
  Teton: { website: "teton.com" },
  Tibber: { website: "tibber.com" },
  Tomorro: { website: "tomorro.com" },
  Tomorrow: { website: "tomorrow.eu" },
  Torq: { website: "torq.co" },
  Trackman: { website: "trackman.pl" },
  Trustly: { website: "trustly.com" },
  Trustpair: { website: "trustpair.com" },
  Two: { website: "two.dev" },
  Uberall: { website: "uberall.com" },
  Ubimet: { website: "ubimet.com" },
  Unifonic: { website: "unifonic.com" },
  Upvest: { website: "upvest.io" },
  Validio: { website: "validio.io" },
  Veriff: { website: "veriff.com" },
  Verkor: { website: "verkor.com" },
  Vialytics: { website: "vialytics.com" },
  Voodoo: { website: "voodoo.io" },
  Voyado: { website: "voyado.com" },
  WalkMe: { website: "walkme.com" },
  Wamo: { website: "wamo.io" },
  Wayflyer: { website: "wayflyer.com" },
  Yotpo: { website: "yotpo.com" },
  Yubico: { website: "yubico.io" },
  YuLife: { website: "yulife.com" },
  Zenjob: { website: "zenjob.com" },
  Ziina: { website: "ziina.com" },
  Zitec: { website: "zitec.com" },
  Zowie: { website: "zowie.ai" },
};

export function companyMeta(name: string): CompanyMeta {
  return COMPANY_META[name] || {};
}
