// AUTO-GENERATED by gpg_import.py — UK Gender Pay Gap filings (2024),
// public gov.uk data. Display-only context; never blended into medians.
export interface GpgRecord {
  employer: string; year: number;
  medianGapPct: number | null; meanGapPct: number | null;
  employerSize: string | null;
  womenByQuartile: { lower: number | null; lowerMiddle: number | null; upperMiddle: number | null; top: number | null };
  sourceUrl: string;
}
export const GPG_BY_SLUG: Record<string, GpgRecord> = {
  "adidas": {
    "employer": "ADIDAS (U.K.) LIMITED",
    "year": 2024,
    "medianGapPct": 0.0,
    "meanGapPct": 20.2,
    "employerSize": "1000 to 4999",
    "womenByQuartile": {
      "lower": 51.4,
      "lowerMiddle": 48.0,
      "upperMiddle": 54.2,
      "top": 47.0
    },
    "sourceUrl": "https://gender-pay-gap.service.gov.uk/Employer/904"
  },
  "amazon": {
    "employer": "AMAZON UK SERVICES LTD.",
    "year": 2024,
    "medianGapPct": 2.2,
    "meanGapPct": -2.0,
    "employerSize": "20,000 or more",
    "womenByQuartile": {
      "lower": 32.9,
      "lowerMiddle": 32.7,
      "upperMiddle": 27.5,
      "top": 32.6
    },
    "sourceUrl": "https://www.aboutamazon.co.uk/amazons-gender-pay-gap-results"
  },
  "apple": {
    "employer": "APPLE (UK) LIMITED",
    "year": 2024,
    "medianGapPct": 17.0,
    "meanGapPct": 15.0,
    "employerSize": "1000 to 4999",
    "womenByQuartile": {
      "lower": 39.0,
      "lowerMiddle": 25.0,
      "upperMiddle": 17.0,
      "top": 15.0
    },
    "sourceUrl": "https://www.apple.com/legal/more-resources/docs/uk-gender-pay-gap-report-2024.pdf"
  },
  "booking-com": {
    "employer": "BOOKING.COM LIMITED",
    "year": 2024,
    "medianGapPct": 17.0,
    "meanGapPct": 14.0,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 53.0,
      "lowerMiddle": 44.0,
      "upperMiddle": 27.0,
      "top": 36.0
    },
    "sourceUrl": "https://www.booking.com/content/uk-pay-gap.en-gb.html"
  },
  "bosch": {
    "employer": "BOSCH THERMOTECHNOLOGY LTD",
    "year": 2024,
    "medianGapPct": 15.7,
    "meanGapPct": 12.7,
    "employerSize": "1000 to 4999",
    "womenByQuartile": {
      "lower": 31.2,
      "lowerMiddle": 25.0,
      "upperMiddle": 14.6,
      "top": 12.6
    },
    "sourceUrl": "https://gender-pay-gap.service.gov.uk/Employer/2244"
  },
  "cisco": {
    "employer": "CISCO INTERNATIONAL LIMITED",
    "year": 2024,
    "medianGapPct": 13.4,
    "meanGapPct": 13.3,
    "employerSize": "1000 to 4999",
    "womenByQuartile": {
      "lower": 40.1,
      "lowerMiddle": 32.9,
      "upperMiddle": 26.3,
      "top": 21.9
    },
    "sourceUrl": "https://www.cisco.com/c/dam/global/en_uk/about/csr/uk-gender-pay-gap-report-2024.pdf"
  },
  "clearbank": {
    "employer": "CLEARBANK LIMITED",
    "year": 2024,
    "medianGapPct": 21.2,
    "meanGapPct": 13.1,
    "employerSize": "500 to 999",
    "womenByQuartile": {
      "lower": 50.0,
      "lowerMiddle": 38.0,
      "upperMiddle": 31.0,
      "top": 26.0
    },
    "sourceUrl": "https://clear.bank/diversity-equity-inclusion"
  },
  "cloudflare": {
    "employer": "CLOUDFLARE LIMITED",
    "year": 2024,
    "medianGapPct": 21.4,
    "meanGapPct": 22.6,
    "employerSize": "500 to 999",
    "womenByQuartile": {
      "lower": 46.5,
      "lowerMiddle": 30.2,
      "upperMiddle": 21.6,
      "top": 14.7
    },
    "sourceUrl": "https://www.cloudflare.com/en-gb/uk-gender-pay-gap-report/"
  },
  "databricks": {
    "employer": "DATABRICKS U.K. LIMITED",
    "year": 2024,
    "medianGapPct": 26.0,
    "meanGapPct": 14.0,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 48.0,
      "lowerMiddle": 29.0,
      "upperMiddle": 22.0,
      "top": 18.0
    },
    "sourceUrl": "https://www.databricks.com/legal/compliance-ethics"
  },
  "expedia": {
    "employer": "EXPEDIA.COM LIMITED",
    "year": 2024,
    "medianGapPct": 9.4,
    "meanGapPct": 7.2,
    "employerSize": "1000 to 4999",
    "womenByQuartile": {
      "lower": 60.0,
      "lowerMiddle": 53.0,
      "upperMiddle": 49.0,
      "top": 44.0
    },
    "sourceUrl": "https://gender-pay-gap.service.gov.uk/Employer/4838"
  },
  "faculty": {
    "employer": "FACULTY SCIENCE LIMITED",
    "year": 2024,
    "medianGapPct": 14.1,
    "meanGapPct": 15.9,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 59.0,
      "lowerMiddle": 31.0,
      "upperMiddle": 36.0,
      "top": 26.0
    },
    "sourceUrl": "https://gender-pay-gap.service.gov.uk/Employer/23249"
  },
  "farfetch": {
    "employer": "FARFETCH UK LIMITED",
    "year": 2024,
    "medianGapPct": 20.4,
    "meanGapPct": 15.2,
    "employerSize": "500 to 999",
    "womenByQuartile": {
      "lower": 82.0,
      "lowerMiddle": 74.0,
      "upperMiddle": 68.0,
      "top": 62.0
    },
    "sourceUrl": "https://aboutfarfetch.com/media/1926/uk-gender-pay-gap-2024.pdf"
  },
  "gocardless": {
    "employer": "GOCARDLESS LTD",
    "year": 2024,
    "medianGapPct": 16.0,
    "meanGapPct": 19.8,
    "employerSize": "500 to 999",
    "womenByQuartile": {
      "lower": 57.0,
      "lowerMiddle": 52.0,
      "upperMiddle": 33.0,
      "top": 33.0
    },
    "sourceUrl": "https://gocardless.com/about/diversity-inclusion/"
  },
  "google": {
    "employer": "GOOGLE UK LIMITED",
    "year": 2024,
    "medianGapPct": 12.0,
    "meanGapPct": 12.0,
    "employerSize": "5000 to 19,999",
    "womenByQuartile": {
      "lower": 52.0,
      "lowerMiddle": 40.0,
      "upperMiddle": 34.0,
      "top": 29.0
    },
    "sourceUrl": "https://services.google.com/fh/files/misc/google-uk_binary-gender-pay-gap-report-2024_25.pdf"
  },
  "graphcore": {
    "employer": "GRAPHCORE LIMITED",
    "year": 2024,
    "medianGapPct": 24.8,
    "meanGapPct": 26.3,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 26.8,
      "lowerMiddle": 21.1,
      "upperMiddle": 9.7,
      "top": 5.6
    },
    "sourceUrl": "https://gender-pay-gap.service.gov.uk/Employer/19890"
  },
  "ikea": {
    "employer": "IKEA LIMITED",
    "year": 2024,
    "medianGapPct": 3.5,
    "meanGapPct": 5.6,
    "employerSize": "5000 to 19,999",
    "womenByQuartile": {
      "lower": 58.6,
      "lowerMiddle": 56.6,
      "upperMiddle": 48.2,
      "top": 44.1
    },
    "sourceUrl": "https://www.ikea.com/gb/en/files/pdf/35/19/351982b6/ikea-2024-uk-gender-pay-v1.pdf"
  },
  "jobandtalent": {
    "employer": "JOBANDTALENT UK LIMITED",
    "year": 2024,
    "medianGapPct": 15.0,
    "meanGapPct": 37.0,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 71.8,
      "lowerMiddle": 63.6,
      "upperMiddle": 52.6,
      "top": 37.7
    },
    "sourceUrl": "https://www.jobandtalent.co.uk/legal/policies-and-disclosures"
  },
  "kaluza": {
    "employer": "KALUZA LTD",
    "year": 2024,
    "medianGapPct": 12.5,
    "meanGapPct": 11.5,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 47.0,
      "lowerMiddle": 38.0,
      "upperMiddle": 22.0,
      "top": 24.0
    },
    "sourceUrl": "https://kaluza-careers.cdn.prismic.io/kaluza-careers/ZvatDrVsGrYSwE4N_FINAL_DE%26Ireport2024.pdf"
  },
  "linkedin": {
    "employer": "LINKEDIN TECHNOLOGY UK LIMITED",
    "year": 2024,
    "medianGapPct": 6.9,
    "meanGapPct": 12.5,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 52.3,
      "lowerMiddle": 59.8,
      "upperMiddle": 56.2,
      "top": 40.5
    },
    "sourceUrl": "https://news.linkedin.com/content/dam/me/news/en-us/images/Gender_Pay_Gap_Graphic_LinkedIn_UK_2025_Final_Updated.pdf"
  },
  "marshmallow": {
    "employer": "MARSHMALLOW TECHNOLOGY LTD",
    "year": 2024,
    "medianGapPct": 33.4,
    "meanGapPct": 26.4,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 64.0,
      "lowerMiddle": 60.0,
      "upperMiddle": 45.0,
      "top": 33.0
    },
    "sourceUrl": "https://www.marshmallow.com/blog/gender-pay-gap-report-2024-2025"
  },
  "matillion": {
    "employer": "MATILLION LIMITED",
    "year": 2024,
    "medianGapPct": 25.6,
    "meanGapPct": 27.5,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 48.1,
      "lowerMiddle": 31.6,
      "upperMiddle": 17.7,
      "top": 15.4
    },
    "sourceUrl": "https://www.matillion.com/uploads/pdf/2025-Matillion-Gender-Pay-Gap-Report.pdf"
  },
  "microsoft": {
    "employer": "MICROSOFT LIMITED",
    "year": 2024,
    "medianGapPct": 5.3,
    "meanGapPct": 6.6,
    "employerSize": "5000 to 19,999",
    "womenByQuartile": {
      "lower": 41.1,
      "lowerMiddle": 30.9,
      "upperMiddle": 30.1,
      "top": 27.8
    },
    "sourceUrl": "https://www.microsoft.com/en-gb/about/gender-pay-gap/"
  },
  "monzo": {
    "employer": "MONZO BANK LIMITED",
    "year": 2024,
    "medianGapPct": 6.3,
    "meanGapPct": 17.3,
    "employerSize": "1000 to 4999",
    "womenByQuartile": {
      "lower": 53.0,
      "lowerMiddle": 51.7,
      "upperMiddle": 49.5,
      "top": 38.5
    },
    "sourceUrl": "https://monzo.com/blog/an-update-on-our-gender-pay-gap-2024"
  },
  "moonpig": {
    "employer": "MOONPIG GROUP PLC",
    "year": 2024,
    "medianGapPct": 26.9,
    "meanGapPct": 23.5,
    "employerSize": "Less than 250",
    "womenByQuartile": {
      "lower": 54.9,
      "lowerMiddle": 65.5,
      "upperMiddle": 46.1,
      "top": 36.6
    },
    "sourceUrl": "https://www.moonpig.group/media/whipefem/gender-pay-gap-report-2024.pdf"
  },
  "motorway": {
    "employer": "MOTORWAY ONLINE LTD",
    "year": 2024,
    "medianGapPct": 32.4,
    "meanGapPct": 18.7,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 42.2,
      "lowerMiddle": 36.1,
      "upperMiddle": 29.4,
      "top": 18.5
    },
    "sourceUrl": "https://motorway.co.uk/blog/2025/01/29/gender-pay-gap-2"
  },
  "multiverse": {
    "employer": "MULTIVERSE GROUP LIMITED",
    "year": 2024,
    "medianGapPct": 11.1,
    "meanGapPct": 13.0,
    "employerSize": "500 to 999",
    "womenByQuartile": {
      "lower": 65.0,
      "lowerMiddle": 49.6,
      "upperMiddle": 48.8,
      "top": 40.2
    },
    "sourceUrl": "https://www.multiverse.io/en-GB/blog/reporting-our-gender-pay-gap-2024"
  },
  "netflix": {
    "employer": "NETFLIX SERVICES UK LIMITED",
    "year": 2024,
    "medianGapPct": 15.2,
    "meanGapPct": 21.8,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 80.0,
      "lowerMiddle": 68.0,
      "upperMiddle": 62.0,
      "top": 55.0
    },
    "sourceUrl": "https://s22.q4cdn.com/959853165/files/doc_downloads/2025/4/netflix_gender_pay_gap_report_2024.pdf"
  },
  "oracle": {
    "employer": "ORACLE GLOBAL SERVICES LIMITED",
    "year": 2024,
    "medianGapPct": 12.5,
    "meanGapPct": 14.6,
    "employerSize": "1000 to 4999",
    "womenByQuartile": {
      "lower": 36.2,
      "lowerMiddle": 28.6,
      "upperMiddle": 24.6,
      "top": 15.7
    },
    "sourceUrl": "https://www.oracle.com/uk/a/ocom/docs/oracle-global-gender-pay-gap-brochure-2024.pdf"
  },
  "palantir": {
    "employer": "PALANTIR TECHNOLOGIES UK, LTD.",
    "year": 2024,
    "medianGapPct": 16.0,
    "meanGapPct": 9.0,
    "employerSize": "500 to 999",
    "womenByQuartile": {
      "lower": 40.0,
      "lowerMiddle": 23.0,
      "upperMiddle": 19.0,
      "top": 25.0
    },
    "sourceUrl": "https://www.palantir.com/assets/xrfr7uokpv1b/1edmc77v8oiYHDgOWj0kWj/b50841cff1ba9162be0a4d2d8788c18b/UK_GenderPayGap_2024_V3.pdf"
  },
  "paypal": {
    "employer": "PAYPAL LIMITED, UK BRANCH",
    "year": 2024,
    "medianGapPct": 5.5,
    "meanGapPct": 1.8,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 39.0,
      "lowerMiddle": 56.0,
      "upperMiddle": 44.0,
      "top": 45.0
    },
    "sourceUrl": "https://www.paypal.com/uk/webapps/mpp/about"
  },
  "philips": {
    "employer": "PHILIPS ELECTRONICS UK LIMITED",
    "year": 2024,
    "medianGapPct": 3.6,
    "meanGapPct": 6.7,
    "employerSize": "500 to 999",
    "womenByQuartile": {
      "lower": 45.8,
      "lowerMiddle": 30.5,
      "upperMiddle": 35.0,
      "top": 34.3
    },
    "sourceUrl": "https://www.philips.co.uk/a-w/about/environmental-social-governance.html"
  },
  "quantexa": {
    "employer": "QUANTEXA LIMITED",
    "year": 2024,
    "medianGapPct": 18.8,
    "meanGapPct": 21.6,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 40.2,
      "lowerMiddle": 26.2,
      "upperMiddle": 25.5,
      "top": 17.9
    },
    "sourceUrl": "http://www.quantexa.com/assets/x/cc7135ec17/quantexa_uk_gender_pay_gap_report_2024_25.pdf?cv=1742481568765"
  },
  "ryanair": {
    "employer": "Ryanair ltd",
    "year": 2024,
    "medianGapPct": 57.8,
    "meanGapPct": 60.8,
    "employerSize": "1000 to 4999",
    "womenByQuartile": {
      "lower": 46.6,
      "lowerMiddle": 40.3,
      "upperMiddle": 26.1,
      "top": 3.5
    },
    "sourceUrl": "https://investor.ryanair.com/wp-content/uploads/2025/04/Ryanair-UK-Gender-Pay-Gap-Infograph-2024_Final.pdf"
  },
  "sap": {
    "employer": "SAP (UK) LIMITED",
    "year": 2024,
    "medianGapPct": 21.9,
    "meanGapPct": 23.8,
    "employerSize": "1000 to 4999",
    "womenByQuartile": {
      "lower": 50.0,
      "lowerMiddle": 33.0,
      "upperMiddle": 26.0,
      "top": 22.0
    },
    "sourceUrl": "https://www.sap.com/uk/about/csr.html?pdf-asset=0c77f7e0-017f-0010-bca6-c68f7e60039b&page=1"
  },
  "salesforce": {
    "employer": "SALESFORCE UK LIMITED",
    "year": 2024,
    "medianGapPct": 23.5,
    "meanGapPct": 23.9,
    "employerSize": "1000 to 4999",
    "womenByQuartile": {
      "lower": 57.0,
      "lowerMiddle": 39.0,
      "upperMiddle": 29.0,
      "top": 28.0
    },
    "sourceUrl": "https://www.salesforce.com/uk/company/equality/gender-pay-gap/2025/"
  },
  "siemens": {
    "employer": "SIEMENS ENERGY INDUSTRIAL TURBOMACHINERY LIMITED",
    "year": 2024,
    "medianGapPct": 10.6,
    "meanGapPct": 13.7,
    "employerSize": "1000 to 4999",
    "womenByQuartile": {
      "lower": 30.7,
      "lowerMiddle": 14.0,
      "upperMiddle": 18.1,
      "top": 10.2
    },
    "sourceUrl": "https://www.siemens-energy.com/uk/en/home.html"
  },
  "skyscanner": {
    "employer": "SKYSCANNER LIMITED",
    "year": 2024,
    "medianGapPct": 16.6,
    "meanGapPct": 8.9,
    "employerSize": "500 to 999",
    "womenByQuartile": {
      "lower": 55.0,
      "lowerMiddle": 40.0,
      "upperMiddle": 29.0,
      "top": 31.0
    },
    "sourceUrl": "https://www.skyscanner.net/news/gender-pay-report-2024"
  },
  "snowflake": {
    "employer": "SNOWFLAKE COMPUTING U.K. LIMITED",
    "year": 2024,
    "medianGapPct": 34.0,
    "meanGapPct": 48.0,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 47.0,
      "lowerMiddle": 15.0,
      "upperMiddle": 17.0,
      "top": 14.0
    },
    "sourceUrl": "https://gender-pay-gap.service.gov.uk/Employer/23205"
  },
  "sophos": {
    "employer": "SOPHOS LIMITED",
    "year": 2024,
    "medianGapPct": 16.4,
    "meanGapPct": 10.9,
    "employerSize": "500 to 999",
    "womenByQuartile": {
      "lower": 32.4,
      "lowerMiddle": 26.1,
      "upperMiddle": 17.6,
      "top": 25.4
    },
    "sourceUrl": "https://www.sophos.com/en-us/legal/gender-statistics"
  },
  "sportradar": {
    "employer": "SPORTRADAR UK LIMITED",
    "year": 2024,
    "medianGapPct": 5.0,
    "meanGapPct": 5.6,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 17.5,
      "lowerMiddle": 12.7,
      "upperMiddle": 29.1,
      "top": 7.5
    },
    "sourceUrl": "https://gender-pay-gap.service.gov.uk/Employer/21540"
  },
  "spotify": {
    "employer": "SPOTIFY LIMITED",
    "year": 2024,
    "medianGapPct": 16.1,
    "meanGapPct": 13.9,
    "employerSize": "500 to 999",
    "womenByQuartile": {
      "lower": 58.5,
      "lowerMiddle": 52.4,
      "upperMiddle": 32.7,
      "top": 32.4
    },
    "sourceUrl": "https://www.lifeatspotify.com/reports/Spotify-UK-Gender-Pay-Report-2024.pdf"
  },
  "swarco": {
    "employer": "SWARCO UK & IRELAND LTD",
    "year": 2024,
    "medianGapPct": 7.5,
    "meanGapPct": 9.6,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 25.8,
      "lowerMiddle": 14.3,
      "upperMiddle": 12.4,
      "top": 16.2
    },
    "sourceUrl": "https://gender-pay-gap.service.gov.uk/Employer/4342"
  },
  "thought-machine": {
    "employer": "THOUGHT MACHINE GROUP LIMITED",
    "year": 2024,
    "medianGapPct": 19.2,
    "meanGapPct": 21.5,
    "employerSize": "500 to 999",
    "womenByQuartile": {
      "lower": 45.5,
      "lowerMiddle": 18.2,
      "upperMiddle": 19.2,
      "top": 12.1
    },
    "sourceUrl": "https://www.thoughtmachine.net/gender-pay-gap-2024"
  },
  "tiktok": {
    "employer": "TIKTOK INFORMATION TECHNOLOGIES UK LIMITED",
    "year": 2024,
    "medianGapPct": 17.5,
    "meanGapPct": 17.9,
    "employerSize": "1000 to 4999",
    "womenByQuartile": {
      "lower": 61.1,
      "lowerMiddle": 61.0,
      "upperMiddle": 56.8,
      "top": 44.7
    },
    "sourceUrl": "https://gender-pay-gap.service.gov.uk/Employer/20030"
  },
  "trainline": {
    "employer": "TRAINLINE.COM LIMITED",
    "year": 2024,
    "medianGapPct": 23.0,
    "meanGapPct": 20.0,
    "employerSize": "500 to 999",
    "womenByQuartile": {
      "lower": 59.0,
      "lowerMiddle": 44.0,
      "upperMiddle": 28.0,
      "top": 30.0
    },
    "sourceUrl": "https://gender-pay-gap.service.gov.uk/Employer/12885"
  },
  "trustpilot": {
    "employer": "TRUSTPILOT LTD",
    "year": 2024,
    "medianGapPct": 14.0,
    "meanGapPct": 8.4,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 47.0,
      "lowerMiddle": 43.0,
      "upperMiddle": 27.0,
      "top": 34.0
    },
    "sourceUrl": "https://assets.ctfassets.net/dbztug920vik/6VVYzX7cYRwThHfsqeQYwF/ce02a340cd1537970ec0e0f3837a644c/Trustpilot_2024_Gender_Pay_Gap_Report__1_.pdf"
  },
  "ubisoft": {
    "employer": "UBISOFT REFLECTIONS LIMITED",
    "year": 2024,
    "medianGapPct": 16.1,
    "meanGapPct": -2.2,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 28.9,
      "lowerMiddle": 26.5,
      "upperMiddle": 15.3,
      "top": 18.4
    },
    "sourceUrl": "https://gender-pay-gap.service.gov.uk/Employer/19126"
  },
  "wayve": {
    "employer": "WAYVE TECHNOLOGIES LTD",
    "year": 2024,
    "medianGapPct": 6.4,
    "meanGapPct": 1.3,
    "employerSize": "250 to 499",
    "womenByQuartile": {
      "lower": 31.0,
      "lowerMiddle": 33.0,
      "upperMiddle": 17.0,
      "top": 31.0
    },
    "sourceUrl": "https://gender-pay-gap.service.gov.uk/Employer/32457"
  }
};
export function gpgFor(slug: string): GpgRecord | null { return GPG_BY_SLUG[slug] ?? null; }
