# =============================================================================
# COMPANIES — AUTO-GENERATED by resolver.py. Safe to edit by hand.
#
# Each entry: {"name": ..., "ats": ..., "token": ...}
#   ats   = greenhouse | lever | ashby | smartrecruiters
#   token = the company's public ID in that ATS.
#
# Companies the resolver could NOT place are commented out at the bottom so
# you can see exactly what failed (private/unknown ATS, renamed token, etc.).
# Re-run `python3 resolver.py` to refresh.
# =============================================================================

COMPANIES = [
    {"name": 'Adyen'                 , "ats": 'greenhouse'      , "token": 'adyen'},
    {"name": 'Monzo'                 , "ats": 'greenhouse'      , "token": 'monzo'},
    {"name": 'Wise'                  , "ats": 'smartrecruiters' , "token": 'Wise'},
    {"name": 'N26'                   , "ats": 'greenhouse'      , "token": 'n26'},
    {"name": 'GoCardless'            , "ats": 'greenhouse'      , "token": 'gocardless'},
    {"name": 'Qonto'                 , "ats": 'lever'           , "token": 'qonto'},
    {"name": 'Pleo'                  , "ats": 'ashby'           , "token": 'pleo'},
    {"name": 'SumUp'                 , "ats": 'greenhouse'      , "token": 'sumup'},
    {"name": 'Mollie'                , "ats": 'ashby'           , "token": 'mollie'},
    {"name": 'Trade Republic'        , "ats": 'greenhouse'      , "token": 'traderepublic'},
    {"name": 'Pennylane'             , "ats": 'ashby'           , "token": 'pennylane'},
    {"name": 'Tide'                  , "ats": 'greenhouse'      , "token": 'tide'},
    {"name": 'Form3'                 , "ats": 'greenhouse'      , "token": 'form3'},
    {"name": 'Griffin'               , "ats": 'ashby'           , "token": 'griffin'},
    {"name": 'Lunar'                 , "ats": 'ashby'           , "token": 'lunar'},
    {"name": 'Zopa'                  , "ats": 'lever'           , "token": 'zopa'},
    {"name": 'Marshmallow'           , "ats": 'ashby'           , "token": 'marshmallow'},
    {"name": 'ComplyAdvantage'       , "ats": 'greenhouse'      , "token": 'complyadvantage'},
    {"name": 'Mistral AI'            , "ats": 'lever'           , "token": 'mistral'},
    {"name": 'ElevenLabs'            , "ats": 'ashby'           , "token": 'elevenlabs'},
    {"name": 'Synthesia'             , "ats": 'ashby'           , "token": 'synthesia'},
    {"name": 'Wayve'                 , "ats": 'greenhouse'      , "token": 'wayve'},
    {"name": 'DeepL'                 , "ats": 'ashby'           , "token": 'deepl'},
    {"name": 'PolyAI'                , "ats": 'greenhouse'      , "token": 'polyai'},
    {"name": 'Stability AI'          , "ats": 'greenhouse'      , "token": 'stabilityai'},
    {"name": 'Faculty'               , "ats": 'ashby'           , "token": 'faculty'},
    {"name": 'Speechmatics'          , "ats": 'greenhouse'      , "token": 'speechmatics'},
    {"name": 'Helsing'               , "ats": 'greenhouse'      , "token": 'helsing'},
    {"name": 'GitLab'                , "ats": 'greenhouse'      , "token": 'gitlab'},
    {"name": 'Grafana Labs'          , "ats": 'greenhouse'      , "token": 'grafanalabs'},
    {"name": 'PostHog'               , "ats": 'ashby'           , "token": 'posthog'},
    {"name": 'n8n'                   , "ats": 'ashby'           , "token": 'n8n'},
    {"name": 'Tinybird'              , "ats": 'lever'           , "token": 'tinybird'},
    {"name": 'Algolia'               , "ats": 'greenhouse'      , "token": 'algolia'},
    {"name": 'Celonis'               , "ats": 'greenhouse'      , "token": 'celonis'},
    {"name": 'Dataiku'               , "ats": 'greenhouse'      , "token": 'dataiku'},
    {"name": 'Collibra'              , "ats": 'greenhouse'      , "token": 'collibra'},
    {"name": 'Aircall'               , "ats": 'lever'           , "token": 'aircall'},
    {"name": 'Ledger'                , "ats": 'lever'           , "token": 'ledger'},
    {"name": 'Quantexa'              , "ats": 'ashby'           , "token": 'quantexa'},
    {"name": 'Matillion'             , "ats": 'lever'           , "token": 'matillion'},
    {"name": 'Delivery Hero'         , "ats": 'smartrecruiters' , "token": 'DeliveryHero'},
    {"name": 'Deliveroo'             , "ats": 'ashby'           , "token": 'deliveroo'},
    {"name": 'GetYourGuide'          , "ats": 'greenhouse'      , "token": 'getyourguide'},
    {"name": 'Omio'                  , "ats": 'smartrecruiters' , "token": 'Omio'},
    {"name": 'Wolt'                  , "ats": 'greenhouse'      , "token": 'wolt'},
    {"name": 'Back Market'           , "ats": 'ashby'           , "token": 'backmarket'},
    {"name": 'Trustpilot'            , "ats": 'greenhouse'      , "token": 'trustpilot'},
    {"name": 'Vestiaire Collective'  , "ats": 'lever'           , "token": 'vestiairecollective'},
    {"name": 'Sorare'                , "ats": 'ashby'           , "token": 'sorare'},
    {"name": 'Moonpig'               , "ats": 'lever'           , "token": 'moonpig'},
    {"name": 'HelloFresh'            , "ats": 'greenhouse'      , "token": 'hellofresh'},
    {"name": 'Gousto'                , "ats": 'smartrecruiters' , "token": 'Gousto'},
    {"name": 'Blablacar'             , "ats": 'lever'           , "token": 'blablacar'},
    {"name": 'Skyscanner'            , "ats": 'greenhouse'      , "token": 'skyscanner'},
    {"name": 'Farfetch'              , "ats": 'greenhouse'      , "token": 'farfetch'},
    {"name": 'Doctolib'              , "ats": 'greenhouse'      , "token": 'doctolib'},
    {"name": 'Alan'                  , "ats": 'ashby'           , "token": 'alan'},
    {"name": 'Flo Health'            , "ats": 'greenhouse'      , "token": 'flohealth'},
    {"name": 'Oura'                  , "ats": 'greenhouse'      , "token": 'oura'},
    {"name": 'Personio'              , "ats": 'recruitee'       , "token": 'personio'},
    {"name": 'HiBob'                 , "ats": 'smartrecruiters' , "token": 'HiBob'},
    {"name": 'Remote'                , "ats": 'greenhouse'      , "token": 'remote'},
    {"name": 'Oyster'                , "ats": 'ashby'           , "token": 'oyster'},
    {"name": 'Contentful'            , "ats": 'greenhouse'      , "token": 'contentful'},
    {"name": 'Typeform'              , "ats": 'greenhouse'      , "token": 'typeform'},
    {"name": 'Miro'                  , "ats": 'ashby'           , "token": 'miro'},
    {"name": 'Juro'                  , "ats": 'ashby'           , "token": 'juro'},
    {"name": 'Beamery'               , "ats": 'ashby'           , "token": 'beamery'},
    {"name": 'PayFit'                , "ats": 'teamtailor'      , "token": 'payfit'},
    {"name": 'Swile'                 , "ats": 'lever'           , "token": 'swile'},
    {"name": 'Leapsome'              , "ats": 'ashby'           , "token": 'leapsome'},
    {"name": 'Humaans'               , "ats": 'ashby'           , "token": 'humaans'},
    {"name": 'Pipedrive'             , "ats": 'lever'           , "token": 'pipedrive'},
    {"name": 'Graphcore'             , "ats": 'greenhouse'      , "token": 'graphcore'},
    {"name": 'Truecaller'            , "ats": 'greenhouse'      , "token": 'truecaller'},
    {"name": 'Cognite'               , "ats": 'greenhouse'      , "token": 'cognite'},
    {"name": 'Contentsquare'         , "ats": 'lever'           , "token": 'contentsquare'},
    {"name": 'Peak'                  , "ats": 'greenhouse'      , "token": 'peak'},
    {"name": 'Aleph Alpha'           , "ats": 'ashby'           , "token": 'alephalpha'},
    {"name": 'Poolside'              , "ats": 'ashby'           , "token": 'poolside'},
    {"name": 'H Company'             , "ats": 'ashby'           , "token": 'hcompany'},
    {"name": 'Photoroom'             , "ats": 'ashby'           , "token": 'photoroom'},
    {"name": 'Nabla'                 , "ats": 'ashby'           , "token": 'nabla'},
    {"name": 'Owkin'                 , "ats": 'ashby'           , "token": 'owkin'},
    {"name": 'Black Forest Labs'     , "ats": 'greenhouse'      , "token": 'blackforestlabs'},
    {"name": 'Parloa'                , "ats": 'greenhouse'      , "token": 'parloa'},
    {"name": 'Langdock'              , "ats": 'ashby'           , "token": 'langdock'},
    {"name": 'DeepJudge'             , "ats": 'ashby'           , "token": 'deepjudge'},
    {"name": 'Dust'                  , "ats": 'ashby'           , "token": 'dust'},
    {"name": 'Gladia'                , "ats": 'ashby'           , "token": 'gladia'},
    {"name": 'Zilch'                 , "ats": 'ashby'           , "token": 'zilch'},
    {"name": 'Cleo'                  , "ats": 'greenhouse'      , "token": 'cleo'},
    {"name": 'Freetrade'             , "ats": 'ashby'           , "token": 'freetrade'},
    {"name": 'Codat'                 , "ats": 'ashby'           , "token": 'codat'},
    {"name": 'TrueLayer'             , "ats": 'greenhouse'      , "token": 'truelayer'},
    {"name": 'Raisin'                , "ats": 'greenhouse'      , "token": 'raisin'},
    {"name": 'Bitpanda'              , "ats": 'greenhouse'      , "token": 'bitpanda'},
    {"name": 'Wamo'                  , "ats": 'teamtailor'      , "token": 'wamo'},
    {"name": 'Bunq'                  , "ats": 'recruitee'       , "token": 'bunq'},
    {"name": 'Swan'                  , "ats": 'ashby'           , "token": 'swan'},
    {"name": 'Memo Bank'             , "ats": 'teamtailor'      , "token": 'memobank'},
    {"name": 'Sentry'                , "ats": 'ashby'           , "token": 'sentry'},
    {"name": 'Checkly'               , "ats": 'ashby'           , "token": 'checkly'},
    {"name": 'Meilisearch'           , "ats": 'teamtailor'      , "token": 'meilisearch'},
    {"name": 'Scaleway'              , "ats": 'lever'           , "token": 'scaleway'},
    {"name": 'Weaviate'              , "ats": 'ashby'           , "token": 'weaviate'},
    {"name": 'Neo4j'                 , "ats": 'greenhouse'      , "token": 'neo4j'},
    {"name": 'Camunda'               , "ats": 'ashby'           , "token": 'camunda'},
    {"name": 'Storyblok'             , "ats": 'greenhouse'      , "token": 'storyblok'},
    {"name": 'Hygraph'               , "ats": 'recruitee'       , "token": 'hygraph'},
    {"name": 'Pigment'               , "ats": 'lever'           , "token": 'pigment'},
    {"name": 'Payflows'              , "ats": 'recruitee'       , "token": 'payflows'},
    {"name": '360Learning'           , "ats": 'lever'           , "token": '360learning'},
    {"name": 'Yousign'               , "ats": 'teamtailor'      , "token": 'yousign'},
    {"name": 'Agicap'                , "ats": 'lever'           , "token": 'agicap'},
    {"name": 'Sellsy'                , "ats": 'recruitee'       , "token": 'sellsy'},
    {"name": 'Skello'                , "ats": 'teamtailor'      , "token": 'skello'},
    {"name": 'Shine'                 , "ats": 'teamtailor'      , "token": 'shine'},
    {"name": 'Upflow'                , "ats": 'ashby'           , "token": 'upflow'},
    {"name": 'Intercom'              , "ats": 'greenhouse'      , "token": 'intercom'},
    {"name": 'Klaxoon'               , "ats": 'greenhouse'      , "token": 'klaxoon'},
    {"name": 'Notion'                , "ats": 'ashby'           , "token": 'notion'},
    {"name": 'Whereby'               , "ats": 'lever'           , "token": 'whereby'},
    {"name": 'Superside'             , "ats": 'lever'           , "token": 'superside'},
    {"name": 'Too Good To Go'        , "ats": 'greenhouse'      , "token": 'toogoodtogo'},
    {"name": 'Heetch'                , "ats": 'lever'           , "token": 'heetch'},
    {"name": 'Cabify'                , "ats": 'greenhouse'      , "token": 'cabify'},
    {"name": 'Free Now'              , "ats": 'greenhouse'      , "token": 'freenow'},
    {"name": 'Flink'                 , "ats": 'ashby'           , "token": 'flink'},
    {"name": 'Picnic'                , "ats": 'smartrecruiters' , "token": 'Picnic'},
    {"name": 'Rohlik'                , "ats": 'ashby'           , "token": 'rohlik'},
    {"name": 'Ankorstore'            , "ats": 'ashby'           , "token": 'ankorstore'},
    {"name": 'Mirakl'                , "ats": 'greenhouse'      , "token": 'mirakl'},
    {"name": 'Veepee'                , "ats": 'lever'           , "token": 'veepee'},
    {"name": 'Kaia Health'           , "ats": 'smartrecruiters' , "token": 'KaiaHealth'},
    {"name": 'Avi Medical'           , "ats": 'greenhouse'      , "token": 'avimedical'},
    {"name": 'Tines'                 , "ats": 'greenhouse'      , "token": 'tines'},
    {"name": 'Detectify'             , "ats": 'teamtailor'      , "token": 'detectify'},
    {"name": 'Truffle Security'      , "ats": 'greenhouse'      , "token": 'trufflesecurity'},
    {"name": 'Hoxhunt'               , "ats": 'ashby'           , "token": 'hoxhunt'},
    {"name": 'CybelAngel'            , "ats": 'teamtailor'      , "token": 'cybelangel'},
    {"name": 'Spotify'               , "ats": 'lever'           , "token": 'spotify'},
    {"name": 'Epidemic Sound'        , "ats": 'ashby'           , "token": 'epidemic-sound'},
    {"name": 'Kognity'               , "ats": 'ashby'           , "token": 'kognity'},
    {"name": 'Mentimeter'            , "ats": 'greenhouse'      , "token": 'mentimeter'},
    {"name": 'Voyado'                , "ats": 'teamtailor'      , "token": 'voyado'},
    {"name": 'Templafy'              , "ats": 'teamtailor'      , "token": 'templafy'},

    # ---- Unresolved (no ATS returned jobs) ----
    # {"name": 'Revolut'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Klarna'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Spendesk'              , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Starling Bank'         , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Modulr'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Onfido'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Builder.ai'            , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Cradle'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Snyk'                  , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Aiven'                 , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Featurespace'          , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Glovo'                 , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Vinted'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Depop'                 , "ats": None, "token": None},  # resolver: not found
    # {"name": 'ManoMano'              , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Taxfix'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Kry'                   , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Huma'                  , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Cera'                  , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Factorial'             , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Multiplier'            , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Pitch'                 , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Mews'                  , "ats": None, "token": None},  # resolver: not found
    # {"name": 'TravelPerk'            , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Darktrace'             , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Kahoot'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Hugging Face'          , "ats": None, "token": None},  # resolver: not found
    # {"name": 'LightOn'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Kyutai'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Lakera'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Giskard'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Finegrain'             , "ats": None, "token": None},  # resolver: not found
    # {"name": 'LeChat'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Unbabel'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Curve'                 , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Plum'                  , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Moneybox'              , "ats": None, "token": None},  # resolver: not found
    # {"name": 'PrimaryBid'            , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Yapily'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Volt'                  , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Vivid Money'           , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Solaris'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Scalable Capital'      , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Ramp Network'          , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Payhawk'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Finom'                 , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Alma'                  , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Lydia'                 , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Defacto'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Appsmith'              , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Directus'              , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Strapi'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Qovery'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Koyeb'                 , "ats": None, "token": None},  # resolver: not found
    # {"name": 'OVHcloud'              , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Upstash'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Qdrant'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Cypress'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Crowdin'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Localazy'              , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Odoo'                  , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Teamleader'            , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Silae'                 , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Combo'                 , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Regate'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Libeo'                 , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Front'                 , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Matomo'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Slite'                 , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Voi'                   , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Tier Mobility'         , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Bolt'                  , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Getir'                 , "ats": None, "token": None},  # resolver: not found
    # {"name": 'La Fourche'            , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Zalando'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'About You'             , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Otto Group'            , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Douglas'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Idealo'                , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Zava'                  , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Ada Health'            , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Doctorly'              , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Patient21'             , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Medwing'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Heartbeat Medical'     , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Gatewatcher'           , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Dixa'                  , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Supermetrics'          , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Smartly'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Swappie'               , "ats": None, "token": None},  # resolver: not found
    # {"name": 'Silo AI'               , "ats": None, "token": None},  # resolver: not found
]
